name: lifeline_integrated
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  salomon_bottom_bar: ^2.0.0
  table_calendar: ^2.3.0
  cached_network_image: ^2.2.0+1
  material_design_icons_flutter: 4.0.5755

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat/Montserrat-Thin.ttf
          weight: 100
        - asset: fonts/Montserrat/Montserrat-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: fonts/Montserrat/Montserrat-ExtraLight.ttf
          weight: 200
        - asset: fonts/Montserrat/Montserrat-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: fonts/Montserrat/Montserrat-Light.ttf
          weight: 300
        - asset: fonts/Montserrat/Montserrat-LightItalic.ttf
          weight: 300
          style: italic
        - asset: fonts/Montserrat/Montserrat-Regular.ttf
          weight: 400
        - asset: fonts/Montserrat/Montserrat-Medium.ttf
          weight: 500
        - asset: fonts/Montserrat/Montserrat-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: fonts/Montserrat/Montserrat-SemiBold.ttf
          weight: 600
        - asset: fonts/Montserrat/Montserrat-SemiBoldItalic.ttf
          weight: 600
        - asset: fonts/Montserrat/Montserrat-Bold.ttf
          weight: 700
        - asset: fonts/Montserrat/Montserrat-BoldItalic.ttf
          weight: 700
        - asset: fonts/Montserrat/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: fonts/Montserrat/Montserrat-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: fonts/Montserrat/Montserrat-Black.ttf
          weight: 900
        - asset: fonts/Montserrat/Montserrat-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: fonts/Montserrat/Montserrat-Italic.ttf
          style: italic

    - family: Oxygen
      fonts:
        - asset: fonts/Oxygen/Oxygen-Bold.ttf
          weight: 700
        - asset: fonts/Oxygen/Oxygen-Light.ttf
          weight: 300
        - asset: fonts/Oxygen/Oxygen-Regular.ttf
          weight: 400
    - family: Roboto
      fonts:
        - asset: fonts/Roboto/Roboto-Black.ttf
          weight: 900
        - asset: fonts/Roboto/Roboto-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: fonts/Roboto/Roboto-Bold.ttf
          weight: 700
        - asset: fonts/Roboto/Roboto-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: fonts/Roboto/Roboto-Italic.ttf
          style: italic
        - asset: fonts/Roboto/Roboto-Light.ttf
          weight: 300
        - asset: fonts/Roboto/Roboto-LightItalic.ttf
          weight: 300
          style: italic
        - asset: fonts/Roboto/Roboto-Medium.ttf
          weight: 500
          style: italic
        - asset: fonts/Roboto/Roboto-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: fonts/Roboto/Roboto-Regular.ttf
          weight: 400
        - asset: fonts/Roboto/Roboto-Thin.ttf
          weight: 100
        - asset: fonts/Roboto/Roboto-ThinItalic.ttf
          weight: 100
          style: italic

    - family: Barbara
      fonts:
        - asset: fonts/Barabara.otf
